### PR TITLE
fixed strange problem with webpack.

### PR DESCRIPTION
**Pull request by btbxbob**
https://github.com/fshost/node-dir/issues/46

### CODE REVIEW

**Comment by AckerApple** [comment]
Thank you. I don't think I ever published this fork to npm and should do so. @fshost must have fallen off of earth. Is that why you issued a pull request here because no action at original package?

Do you think I should publish to npm as ack-node-dir? Any opinions?

Thank you much. I'll let you close the issue

**Comment by AckerApple** [comment]
My fork has been npm published as path-reader. Github package name will eventually change too at some point.

https://www.npmjs.com/package/path-reader

**Comment by btbxbob** [comment]
Hello, i forked from your repo because you fixed the UTF-8 BOM problem of paths.js first ([link](https://github.com/AckerApple/node-dir/commit/1a21c09ffaae14265196e4a50bfc60db0552818e)).  

yes i think you should publish to npm because the original one is not working with webpack, witch is very common now.

**Comment by AckerApple** [comment]
package has been renamed to path-reader . A node-dir deprecation system has been put in place.

@btbxbob, thank you for your input and pull request

**Pull request merged**
